### ISSUE TITLE
Sendtarget causes both the current character and the intended character to do the command

### ISSUE THREAD

**Issue by Chaotic** [DiscipleOfEris/Windower4Addons#3]
On Asen (72 PLD) with Chaoticunreal (75 rdm) with the alias ch sta Chaoticunreal defined.
doing //ch cure4 me (or //ch //cure4 me) causes both characters to cast cure4 on Asen.

Also happened with curingwaltz so I don't think the command effects it

**Comment by DiscipleOfEris** [comment]
I was finally seeing this effect myself today. Haven't had a chance to investigate it yet.

**Comment by Chaotic** [comment]
Any news on this?

**Comment by DiscipleOfEris** [comment]
Unfortunately, that "today" in my last message was the only time I experienced it. I wasn't able to reproduce it when I went to test it, and haven't noticed it again since...

I have noticed a *similar* bug though when using other addons that inject comments, such as AutoRA. If it triggers while doing a `<stpc>` or other subtargeting command, it disrupts the state and prevents the command from being processed by the addon.

Only thing I can ask is about other addons you might be using when encountering the bug.

**Comment by Chaotic** [comment]
I'll play around and see if it is another addon causing the issues since I'm able to reproduce it 100% of the time.

**Comment by Chaotic** [comment]
Looks like it only happens with gearswap so I'll go through that and see if I can figure out wth is going on.

**Comment by Chaotic** [comment]
Closing the loop on this here looks like plugin_manager just loads the plugin/addons in alphabetical order so even having gearswap at the bottom of the list it was still being loaded before sendtarget.  Reloading gearswap fixes the problem.
